### PR TITLE
inventory view in frontend

### LINKED ISSUE #2: List everything stored in depot
Implement the functionality to list everything that is stored in the depot.

### PR DESCRIPTION
**Pull request by mrader1248**

### CODE REVIEW

**Comment by ver4p** [comment]
initial loading of page ignores rows per page

**Comment by mrader1248** [comment]
Sorry for that. The property `items-per-page` of `v-data-table` was set to the invalid value of 20. It is now set to 5, which should be valid.

**Review by ver4p — DISMISSED** [review]
Works properly.

**Review by ver4p — CHANGES_REQUESTED** [review]
Status code 400 and 500 automatically end up in catch-block. Is else-block really required?

**Comment by mrader1248** [comment]
Apparently, `catch` is called whenever the HTTP status code is not 2xx. Unfortunately, the Axios API is rather poorly documented and does not explicitly mention this behaviour. I removed the if-else-block testing for status 200, which should be safe as calling the function `then` with an object `response` without a property `data` raises an error and ends up in the function `catch`.

**Review by ver4p — APPROVED** [review]

**Pull request merged**
